USE [master]
GO
/****** Object:  Database [CommunityLibraryDB]    Script Date: 10/03/2026 1:41:10 PM ******/
CREATE DATABASE [CommunityLibraryDB]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'CommunityLibraryDB', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CommunityLibraryDB.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'CommunityLibraryDB_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\CommunityLibraryDB_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [CommunityLibraryDB] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [CommunityLibraryDB].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [CommunityLibraryDB] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET ARITHABORT OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [CommunityLibraryDB] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [CommunityLibraryDB] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET  ENABLE_BROKER 
GO
ALTER DATABASE [CommunityLibraryDB] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [CommunityLibraryDB] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET RECOVERY FULL 
GO
ALTER DATABASE [CommunityLibraryDB] SET  MULTI_USER 
GO
ALTER DATABASE [CommunityLibraryDB] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [CommunityLibraryDB] SET DB_CHAINING OFF 
GO
ALTER DATABASE [CommunityLibraryDB] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [CommunityLibraryDB] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [CommunityLibraryDB] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [CommunityLibraryDB] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'CommunityLibraryDB', N'ON'
GO
ALTER DATABASE [CommunityLibraryDB] SET QUERY_STORE = OFF
GO
USE [CommunityLibraryDB]
GO
/****** Object:  Table [dbo].[Books]    Script Date: 10/03/2026 1:41:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Books](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Title] [nvarchar](200) NOT NULL,
	[Author] [nvarchar](150) NOT NULL,
	[ISBN] [nvarchar](50) NOT NULL,
	[Category] [nvarchar](100) NOT NULL,
	[TotalCopies] [int] NOT NULL,
	[AvailableCopies] [int] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Loans]    Script Date: 10/03/2026 1:41:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Loans](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[BookId] [int] NOT NULL,
	[MemberId] [int] NOT NULL,
	[BorrowedDate] [datetime2](7) NOT NULL,
	[DueDate] [datetime2](7) NOT NULL,
	[ReturnedDate] [datetime2](7) NULL,
	[Status] [nvarchar](20) NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[Members]    Script Date: 10/03/2026 1:41:10 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Members](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[FullName] [nvarchar](150) NOT NULL,
	[Email] [nvarchar](150) NOT NULL,
	[MembershipType] [nvarchar](20) NOT NULL,
	[DateJoined] [date] NOT NULL,
	[IsActive] [bit] NOT NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[Loans]  WITH CHECK ADD  CONSTRAINT [FK_Loans_Books] FOREIGN KEY([BookId])
REFERENCES [dbo].[Books] ([Id])
GO
ALTER TABLE [dbo].[Loans] CHECK CONSTRAINT [FK_Loans_Books]
GO
ALTER TABLE [dbo].[Loans]  WITH CHECK ADD  CONSTRAINT [FK_Loans_Members] FOREIGN KEY([MemberId])
REFERENCES [dbo].[Members] ([Id])
GO
ALTER TABLE [dbo].[Loans] CHECK CONSTRAINT [FK_Loans_Members]
GO
ALTER TABLE [dbo].[Books]  WITH CHECK ADD  CONSTRAINT [CK_Books_AvailableCopies] CHECK  (([AvailableCopies]>=(0)))
GO
ALTER TABLE [dbo].[Books] CHECK CONSTRAINT [CK_Books_AvailableCopies]
GO
ALTER TABLE [dbo].[Books]  WITH CHECK ADD  CONSTRAINT [CK_Books_AvailableNotMoreThanTotal] CHECK  (([AvailableCopies]<=[TotalCopies]))
GO
ALTER TABLE [dbo].[Books] CHECK CONSTRAINT [CK_Books_AvailableNotMoreThanTotal]
GO
ALTER TABLE [dbo].[Books]  WITH CHECK ADD  CONSTRAINT [CK_Books_TotalCopies] CHECK  (([TotalCopies]>=(0)))
GO
ALTER TABLE [dbo].[Books] CHECK CONSTRAINT [CK_Books_TotalCopies]
GO
ALTER TABLE [dbo].[Loans]  WITH CHECK ADD  CONSTRAINT [CK_Loans_Status] CHECK  (([Status]='Overdue' OR [Status]='Returned' OR [Status]='Borrowed'))
GO
ALTER TABLE [dbo].[Loans] CHECK CONSTRAINT [CK_Loans_Status]
GO
ALTER TABLE [dbo].[Members]  WITH CHECK ADD  CONSTRAINT [CK_Members_MembershipType] CHECK  (([MembershipType]='Faculty' OR [MembershipType]='Student'))
GO
ALTER TABLE [dbo].[Members] CHECK CONSTRAINT [CK_Members_MembershipType]
GO
USE [master]
GO
ALTER DATABASE [CommunityLibraryDB] SET  READ_WRITE 
GO
